#!/bin/bash -l
#SBATCH --job-name="petsc_test"
#SBATCH --account="s1212"
#SBATCH --time=10:00:00
#SBATCH --nodes=4
#SBATCH --partition=normal
#SBATCH --constraint=gpu
export MPICH_RDMA_ENABLED_CUDA=1

export MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_ASYNC_PROGRESS=1


srun ./main

