#!/bin/bash -l
#SBATCH --job-name="iter_test"
#SBATCH --account="s1212"
#SBATCH --time=10:00:00
#SBATCH --nodes=4
#SBATCH --partition=normal
#SBATCH --constraint=gpu

export MPICH_RDMA_ENABLED_CUDA=1

srun ./main -use_gpu_aware_mpi 0

